language: node_js

node_js:
  - "9"

before_install:
  - npm i -g npm@5.6.0
  - npm install -g detox-cli
  - npm install -g react-native-cli
  - brew tap wix/brew
  - brew install applesimutils

cache:
  directories:
    - "node_modules"

script:
  - npm test
